---
apiVersion: v1
kind: Namespace
metadata:
  name: ch-git
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: git
  namespace: ch-git
spec:
  type: Git
  pathname: https://github.com/philipwu08/testrepo.git
---
apiVersion: v1
kind: Namespace
metadata:
  name: parentsub
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: git-sub
  namespace: parentsub
  annotations: 
    apps.open-cluster-management.io/cluster-admin: "true"
    apps.open-cluster-management.io/github-path: secondsub
spec:
  channel: ch-git/git
  placement:
    placementRef:
      name: dev-cluster
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: dev-cluster
  namespace: parentsub
spec:
  clusterSelector:
    matchLabels:
      local-cluster: "true"
