---
apiVersion: v1
kind: Namespace
metadata:
  name: git-sub-ns
---
apiVersion: v1
kind: Namespace
metadata:
  name: ch-git
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: git-sub-app
  namespace: git-sub-ns
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchLabels:
      name: git-sub
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: git-helm
  namespace: ch-git
  labels:
    name: git-sub
spec:
  type: Git
  pathname: https://github.com/open-cluster-management/multicloud-operators-subscription
  configMapRef:
    name: helm-chart
    kind: configmap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-chart
  namespace: ch-git
  labels:
    name: git-sub
data:
  path: test/github/helmcharts/chart1
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: towhichcluster
  namespace: git-sub-ns
  labels:
    name: git-sub
spec:
  clusterReplicas: 1
  clusterLabels:
    matchLabels:
      environment: Dev
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: git-sub
  namespace: git-sub-ns
  labels:
    name: git-sub
spec:
  channel: ch-git/git-helm
  placement:
    placementRef: 
      name: towhichcluster
      kind: PlacementRule
