apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  name: simple
spec:
  channel: dev/dev-helmrepo
  name: nginx-ingress
  placement:
    local: false
  packageOverrides:
  - packageName: nginx-ingress
    packageOverrides:
    - path: spec
      value:
        defaultBackend:
          replicaCount: 3