apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: app.ibm.com/v1alpha1
kind: Channel
metadata:
  name: dev-helmrepo
  namespace: dev
spec:
    type: HelmRepo
    pathname: http://kubernetes-charts.storage.googleapis.com/
    configRef: 
      name: skip-cert-verify
      apiVersion: v1
      kind: ConfigMap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: skip-cert-verify
  namespace: dev
data:
  insecureSkipVerify: "true"
---
apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  name: simple
spec:
  channel: dev/dev-helmrepo
  name: nginx-ingress
  placement:
    local: false
  packageOverrides:
  - packageName: nginx-ingress
    packageOverrides:
    - path: spec.values
      value: |
        defaultBackend:
          replicaCount: 3
