apiVersion: v1
kind: Namespace
metadata:
  name: dev
spec:
---
apiVersion: app.ibm.com/v1alpha1
kind: Channel
metadata:
  name: dev-helmrepo
  namespace: dev
spec:
    type: HelmRepo
    pathname: https://kubernetes-charts.storage.googleapis.com/
---
apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  name: simple
spec:
  channel: dev/dev-helmrepo
  name: nginx-ingress
