apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: subscriptionstatuses.apps.open-cluster-management.io
spec:
  group: apps.open-cluster-management.io
  names:
    kind: SubscriptionStatus
    listKind: SubscriptionStatusList
    plural: subscriptionstatuses
    shortNames:
    - appsubstatus
    singular: subscriptionstatus
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          statuses:
            description: Statuses represents all the resources deployed by the subscription per cluster
            properties:
              packages:
                additionalProperties:
                  description: SubscriptionUnitStatus defines status of a package deployment.
                  properties:
                    lastUpdateTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    phase:
                      type: string
                    pkgkind:
                      type: string
                    pkgnamespace:
                      type: string
                  required:
                  - lastUpdateTime
                  type: object
                type: object
            type: object
          summary:
            properties:
              deployed:
                description: ClusterSummary defines status of a package deployment.
                properties:
                  clusters:
                    items:
                      type: string
                    type: array
                  count:
                    type: integer
                type: object
              failed:
                description: ClusterSummary defines status of a package deployment.
                properties:
                  clusters:
                    items:
                      type: string
                    type: array
                  count:
                    type: integer
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
