apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: multicloud-operators-subscription
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
