apiVersion: apps/v1
kind: Deployment
metadata:
  name: multicloud-operators-subscription
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: multicloud-operators-subscription
  template:
    metadata:
      labels:
        name: multicloud-operators-subscription
    spec:
      serviceAccountName: multicloud-operators-subscription
      containers:
        - name: multicloud-operators-subscription
          image: quay.io/multicloudlab/multicloud-operators-subscription
          command:
          - /multicloud-operators-subscription
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "multicloud-operators-subscription"
          resources:
              requests:
                cpu: 5m
                memory: 5Mi
              limits:
                cpu: 10m
                memory: 256Mi
