apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: nginx-sub
spec:
  channel: dev/dev-helmrepo
  name: nginx-ingress
  placement:
    clusterSelector:
      matchLabels:
        env: dev
  packageFilter:
    version: "1.36.3"
