apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: ansible-hook
  namespace: ansible-pre-post
  labels:
    app: ansible
  annotations:
    apps.open-cluster-management.io/github-path: examples/ansible/resources
    apps.open-cluster-management.io/github-branch: master
spec:
  channel: ansible-pre-post/git
  placement:
    placementRef:
      kind: PlacementRule
      name: non-local-cluster
