apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: subscriptions.app.ibm.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    description: subscription status
    name: Status
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: app.ibm.com
  names:
    kind: Subscription
    listKind: SubscriptionList
    plural: subscriptions
    singular: subscription
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            channel:
              type: string
            name:
              description: To specify 1 package in channel
              type: string
            overrides:
              description: for hub use only to specify the overrides when apply to
                clusters
              items:
                properties:
                  clusterName:
                    type: string
                  clusterOverrides:
                    items:
                      type: object
                    minItems: 1
                    type: array
                required:
                - clusterName
                - clusterOverrides
                type: object
              type: array
            packageFilter:
              description: To specify more than 1 package in channel
              properties:
                annotations:
                  additionalProperties:
                    type: string
                  type: object
                filterRef:
                  type: object
                labelSelector:
                  type: object
                version:
                  pattern: ([0-9]+)((\.[0-9]+)(\.[0-9]+)|(\.[0-9]+)?(\.[xX]))$
                  type: string
              type: object
            packageOverrides:
              description: To provide flexibility to override package in channel with
                local input
              items:
                properties:
                  packageName:
                    type: string
                  packageOverrides:
                    items:
                      type: object
                    minItems: 1
                    type: array
                required:
                - packageName
                - packageOverrides
                type: object
              type: array
            placement:
              description: For hub use only, to specify which clusters to go to
              properties:
                clusterSelector:
                  type: object
                clusters:
                  items:
                    properties:
                      name:
                        type: string
                    required:
                    - name
                    type: object
                  type: array
                local:
                  type: boolean
                placementRef:
                  type: object
              type: object
          required:
          - channel
          type: object
        status:
          properties:
            lastUpdateTime:
              format: date-time
              type: string
            message:
              type: string
            phase:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "make" to regenerate code after modifying
                this file'
              type: string
            reason:
              type: string
            statuses:
              additionalProperties:
                properties:
                  packages:
                    additionalProperties:
                      properties:
                        lastUpdateTime:
                          format: date-time
                          type: string
                        message:
                          type: string
                        phase:
                          description: Phase are Propagated if it is in hub or Subscribed
                            if it is in endpoint
                          type: string
                        reason:
                          type: string
                        resourceStatus:
                          type: object
                      required:
                      - lastUpdateTime
                      type: object
                    type: object
                type: object
              description: For endpoint, it is the status of subscription, key is
                packagename, For hub, it aggregates all status, key is cluster name
              type: object
          required:
          - lastUpdateTime
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
