apiVersion: apps/v1
kind: Deployment
metadata:
  name: multicloud-operators-subscription
  labels:
    name: multicloud-operators-subscription
spec:
  replicas: 1
  selector:
    matchLabels:
      name: multicloud-operators-subscription
  template:
    metadata:
      labels:
        name: multicloud-operators-subscription
    spec:
      serviceAccountName: multicloud-operators
      containers:
        - name: multicloud-operators-subscription
          image: docker.io/rokejungibm/multicloud-operators-subscription:0212a
          ports:
          - containerPort: 8443
          args:
          - --alsologtostderr
          - --cluster-name=ocp-cluster-1
          - --cluster-namespace=ocp-cluster-1
          - --hub-cluster-configfile=/var/run/klusterlet/kubeconfig
          command:
          - /usr/local/bin/multicloud-operators-subscription
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "multicloud-operators-subscription"
          resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 500m
                memory: 512Mi
          volumeMounts:
          - name: multicloud-operators-subscription-tls
            readOnly: true
            mountPath: "/etc/subscription"
          - mountPath: /var/run/klusterlet
            name: klusterlet-config
      volumes:
        - name: multicloud-operators-subscription-tls
          secret:
            defaultMode: 420
            secretName: multicloud-operators-subscription
            items:
            - key: tls.crt
              path: tls.crt
            - key: tls.key
              path: tls.key
        - name: klusterlet-config
          secret:
            defaultMode: 420
            secretName: endpoint-connmgr-hub-kubeconfig
