apiVersion: apps/v1
kind: Deployment
metadata:
  name: uninstall-crd
  namespace: open-cluster-management
  labels:
    name: uninstall-crd
spec:
  replicas: 1
  selector:
    matchLabels:
      name: uninstall-crd
  template:
    metadata:
      labels:
        name: uninstall-crd
    spec:
      containers:
        - name: uninstall-crd
          image: docker.io/rokejungibm/multicloud-operators-subscription:18e
          ports:
          - containerPort: 8443
          command:
          - uninstall-crd 
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "multicloud-operators-subscription"
          resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 500m
                memory: 512Mi
          securityContext:
            capabilities:
              drop:
              - MKNOD
      securityContext:
        seLinuxOptions:
          level: s0:c24,c9
      serviceAccount: multicluster-operators
      serviceAccountName: multicluster-operators
